version: '3.8'

services:
  auth-microservice:
    build: ./auth
    container_name: auth-ms
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db
      - auth-microservice
    networks:
      - app-network

  encdec-microservice:
    build: ./encdec
    container_name: encdec-ms
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
